### ISSUE TITLE
Support Neo Tokyo patch

### ISSUE THREAD

**Issue by tfausak** [tfausak/octane#25]
The Neo Tokyo patch will be released today: http://www.rocketleaguegame.com/news/2016/06/patch-notes-v1-19-title-update-7/

I'm not sure which changes will need to happen, but I imagine at least:
- [x] Add new levels. #27.
- [x] Add new antennas, bodies, decals, and rocket trails. #32
- [x] Investigate item rarities.
- [x] Investigate item attributes (painted and certified). #34

**Comment by tfausak** [comment]
@jjbott: Can you provide another data dump like you did [here](https://github.com/tfausak/octane/issues/8#issuecomment-225446524)? Or, better yet, can you teach me how to make one myself? There are a lot of new items and it would take me a long time to map them manually.

**Comment by jjbott** [comment]
Hi! I'm catching up, I was on vacation for a few days. 

Okay! So, first you need the UPK decryptor linked here: https://www.reddit.com/r/RocketLeague/comments/3v9d10/rocket_league_upk_decryptor_datamined_car_hitbox/ and also UE Explorer from http://eliotvu.com/portfolio/view/21/ue-explorer .

Then decrypt TAGame.upk and open it in UE Explorer. In the Objects tab, in the Content sub-tab, find ProductsDB->Database->ProductsDB. Click it and it'll spit out everything. Use a little regex magic to turn it into JSON, and you're golden.

Assuming there havent been changes to existing data (I didnt check) the new raw data looks like:

```
    Products_New(1278)=none
    Products_New(1279)=Product_TA'ProductsDB.Products.Skin_NeoCar_Pill'
    Products_New(1280)=Product_TA'ProductsDB.Products.Skin_NeoCar_Squid'
    Products_New(1281)=none
    Products_New(1282)=none
    Products_New(1283)=none
    Products_New(1284)=none
    Products_New(1285)=none
    Products_New(1286)=Product_TA'ProductsDB.Products.Body_Aftershock'
    Products_New(1287)=none
    Products_New(1288)=Product_TA'ProductsDB.Products.hat_futureglasses'
    Products_New(1289)=none
    Products_New(1290)=none
    Products_New(1291)=none
    Products_New(1292)=none
    Products_New(1293)=none
    Products_New(1294)=none
    Products_New(1295)=none
    Products_New(1296)=none
    Products_New(1297)=none
    Products_New(1298)=none
    Products_New(1299)=none
    Products_New(1300)=none
    Products_New(1301)=none
    Products_New(1302)=none
    Products_New(1303)=none
    Products_New(1304)=Product_TA'ProductsDB.Products.Flag_DyingLight'
    Products_New(1305)=Product_TA'ProductsDB.Products.Hat_BaseballCap01'
    Products_New(1306)=Product_TA'ProductsDB.Products.Skin_Aftershock_Aztec'
    Products_New(1307)=none
    Products_New(1308)=Product_TA'ProductsDB.Products.Skin_Aftershock_Gato'
    Products_New(1309)=none
    Products_New(1310)=none
    Products_New(1311)=Product_TA'ProductsDB.Products.Skin_Aftershock_Radioactive'
    Products_New(1312)=Product_TA'ProductsDB.Products.Skin_Aftershock_Shockwave'
    Products_New(1313)=Product_TA'ProductsDB.Products.Skin_Aftershock_Tiger'
    Products_New(1314)=Product_TA'ProductsDB.Products.Skin_Aftershock_Wings'
    Products_New(1315)=Product_TA'ProductsDB.Products.WHEEL_Aftershock'
    Products_New(1316)=Product_TA'ProductsDB.Products.Hat_CowboyHat'
    Products_New(1317)=Product_TA'ProductsDB.Products.Body_NeoBike'
    Products_New(1318)=Product_TA'ProductsDB.Products.Boost_Flamethrower_Yellow'
    Products_New(1319)=Product_TA'ProductsDB.Products.Boost_Standard_Green'
    Products_New(1320)=Product_TA'ProductsDB.Products.Skin_NeoBike_Cutter'
    Products_New(1321)=Product_TA'ProductsDB.Products.Skin_NeoBike_FormulaIII'
    Products_New(1322)=Product_TA'ProductsDB.Products.Skin_NeoBike_Kaiju'
    Products_New(1323)=Product_TA'ProductsDB.Products.Skin_NeoBike_MouseCat'
    Products_New(1324)=Product_TA'ProductsDB.Products.Skin_NeoBike_Neo'
    Products_New(1325)=Product_TA'ProductsDB.Products.Skin_NeoBike_Pegasus'
    Products_New(1326)=Product_TA'ProductsDB.Products.Hat_GolfHat'
    Products_New(1327)=none
    Products_New(1328)=Product_TA'ProductsDB.Products.Hat_BaseballCap_Back'
    Products_New(1329)=none
    Products_New(1330)=none
    Products_New(1331)=none
    Products_New(1332)=Product_TA'ProductsDB.Products.Hat_WhiteHat'
    Products_New(1333)=none
    Products_New(1334)=Product_TA'ProductsDB.Products.Boost_Challenger'
    Products_New(1335)=Product_TA'ProductsDB.Products.Boost_Champion'
    Products_New(1336)=Product_TA'ProductsDB.Products.Boost_Prospect'
    Products_New(1337)=Product_TA'ProductsDB.Products.Boost_Star'
    Products_New(1338)=Product_TA'ProductsDB.Products.Hat_TruckerHat'
    Products_New(1339)=Product_TA'ProductsDB.Products.Hat_FlatHat'
    Products_New(1340)=Product_TA'ProductsDB.Products.Skin_Marauder_BigBuck'
    Products_New(1341)=Product_TA'ProductsDB.Products.Skin_Marauder_Stripes'
    Products_New(1342)=Product_TA'ProductsDB.Products.Hat_Visor'
    Products_New(1343)=Product_TA'ProductsDB.Products.Wheel_Marauder'
    Products_New(1344)=none
    Products_New(1345)=Product_TA'ProductsDB.Products.skin_marauder_avalanche'
    Products_New(1346)=Product_TA'ProductsDB.Products.skin_marauder_gasmask'
    Products_New(1347)=none
    Products_New(1348)=Product_TA'ProductsDB.Products.skin_marauder_safari'
    Products_New(1349)=none
    Products_New(1350)=none
    Products_New(1351)=Product_TA'ProductsDB.Products.Antenna_DLZ'
    Products_New(1352)=Product_TA'ProductsDB.Products.skin_marauder_wings'
    Products_New(1353)=none
    Products_New(1354)=none
    Products_New(1355)=none
    Products_New(1356)=none
```

**Comment by tfausak** [comment]
Wow, that is awesome! Thank you!
